name: cpp

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: compilation
        run: |
          chmod +x ci/compilation_cpp.sh
          ./ci/compilation_cpp.sh
          
  test:
   runs-on: ubuntu-latest
   
   steps:
    - uses: actions/checkout@v2
      
    - name: compilation
      run: |
        chmod +x ci/compilation_cpp.sh
        ./ci/compilation_cpp.sh
        
    - name: test
      run:
        ./src/cpp/exemple
