name: java

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: compilation
        run: |
          chmod +x ci/compilation_java.sh
          ./ci/compilation_java.sh -s ./src/java/ -d ./build -n UnitAll

          
      - name: 'Upload Artifact jar'
        uses: actions/upload-artifact@v2
        with:
          name: 'UnitAll jar'
          path: ./build/UnitAll.jar
          retention-days: 1
    
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: compilation
        run: |
          chmod +x ci/compilation_java.sh
          ./ci/compilation_java.sh -s ./src/java/ -d ./build -n UnitAll

      - name: test
        run: |
          pwd
          java -jar ./build/UnitAll.jar
           